baseURL: "http://localhost:1313"
title: "Natixar"
theme: "blox"
languageCode: "en"
defaultContentLanguage: "en"
enableRobotsTXT: true
pagination.pagerSize: 10
buildDrafts: true
googleAnalytics: ""
canonifyURLs: true
build:
  writeStats: true

