# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - identifier: "home"
    name: "Home"
    url: "/#top"
    weight: 1
  - identifier: "solutions"
    name: "Our Technologies"
    url: "/#solutions"
    weight: 2
  - identifier: "applications"
    name: "Application Areas"
    url: "/#applications"
    weight: 3
  - identifier: "vision"
    name: "Field-Based Insights"
    url: "/#vision"
    weight: 4
  # - identifier: "about"
  #   name: "About"
  #   url: "/about/"
  #   weight: 5
  - identifier: "contact"
    name: "Contact"
    url: "/contact/"
    weight: 6
  - identifier: "blog"
    name: "Blog"
    url: "/blog/"
    weight: 7
  # - identifier: "privacy"
  #   name: "Privacy Policy"
  #   url: "/privacy-policy/"
  #   weight: 8
  # - identifier: "terms"
  #   name: "Terms of Service"
  #   url: "/terms-of-service/"
  #   weight: 9
  # - identifier: "sitemap"
  #   name: "Sitemap"
  #   url: "/sitemap.xml"
  #   weight: 10
