# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: "Home"
    url: "/#top"
    weight: 1
  - name: "Our Technologies"
    url: "/#solutions"
    weight: 2
  - name: "Application Areas"
    url: "/#applications"
    weight: 3
  - name: "Field-Based Insights"
    url: "/#vision"
    weight: 4
  - name: "About"
    url: "/#about"
    weight: 5
  - name: "Contact"
    url: "/contact/"
    weight: 6
  - name: "Blog"
    url: "/blog/"
    weight: 7
  # - name: "Privacy Policy"
  #   url: "/privacy-policy/"
  #   weight: 8
  # - name: "Terms of Service"
  #   url: "/terms-of-service/"
  #   weight: 9
  # - name: "Sitemap"
  #   url: "/sitemap.xml"
  #   weight: 10
